sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: "my-dao-dashboard"
    token:
      secure: ${SONAR_TOKEN}
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - cd web
install:
  - yarn install --pure-lockfile
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run test
after_success:
  - sonar-scanner
deploy:
  provider: azure_web_apps
  username: ${AZURE_WA_USERNAME}
  password: ${AZURE_WA_PASSWORD}
  site: ${AZURE_WA_SITE}
  verbose: true
  on: master
