sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: "my-dao-dashboard"
    token:
      secure: ${SONAR_TOKEN}
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - cd web
install:
  - yarn install --pure-lockfile
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run test
  - yarn run build
after_success:
  - sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  on:
    branch: master
