sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: "my-dao-dashboard"
    token:
      secure: ${SONAR_TOKEN}
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - cd web
install:
  - yarn install --pure-lockfile
  - yarn install codecov -g
script:
  - yarn run lint
  - yarn run test
after_success:
  - sonar-scanner
